#!/usr/bin/env python
# -*- coding: utf-8 -*-

import random
import sys
import time

offset = int(sys.argv[2])
random = random.Random()
random.seed(time.time() + offset)

data = ""
if sys.argv[1] == "right":
    data += random.choice(["▙", "▛", "█"])
    data += random.choice(["▚", "▞"])
    data += random.choice(["▗", "▝"])
else:
    data += random.choice(["▖", "▘"])
    data += random.choice(["▚", "▞"])
    data += random.choice(["▜", "▟", "█"])

print(data)
