#!/usr/bin/env bash


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
THIS_PROG="$0"


swagger_jar_path="${DIR}/swagger-codegen-cli.jar"
swagger_url='http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.3.1/swagger-codegen-cli-2.3.1.jar'


if [ ! -f "$swagger_jar_path" ] ; then
    wget -O "$swagger_jar_path" "$swagger_url"
fi


java -jar "$swagger_jar_path" "$@"
